alias dip-list-images='python2 $IMAGE_UTILS_DIR/list_images.py'
alias dip-switch-color='python3 $IMAGE_UTILS_DIR/python/dip/switch_color.py'
alias dip-switch-color-dist='python3 $IMAGE_UTILS_DIR/python/dip/switch_color_distance.py'
alias dip-histogram='python3 $IMAGE_UTILS_DIR/python/dip/color_histogram.py'
alias dip-crop='python3 $IMAGE_UTILS_DIR/python/dip/crop.py'